econciencia/urls.py
from django.contrib import admin


from django.conf.urls.static import static
from django.conf import settings

from canecas import views as caneca_views

from rest_framework import routers


#router = routers.DefaultRouter()
#router.register(r'canecas_api', caneca_views.CanecaApiView)




from django.urls import path, include
from econciencia import views as econciencia_views


urlpatterns = [


    path('admin/', admin.site.urls),


    path('',include(('posts.urls', 'posts'), namespace='posts' )),
    path('users/',include(('users.urls', 'users'), namespace='users' )),
    path('caneca/',include(('canecas.urls', 'canecas'), namespace='canecas' )),


    path('',econciencia_views.home,name="home"),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

posts/urls.py
''' Posts urls'''


#Django

from django.urls import path

#Models

from posts import views


urlpatterns =[
    path(
        route= 'posts/latest_posts/',
        view = views.latest_posts,
        name="latest_posts"
    ),
]

users/urls.py
''' Users views '''


#Django 
from django.urls import path


#Models

from users import views

urlpatterns = [
    path(
        route ='login/',
        view = views.login_view, 
        name="login"
    ),
    path(
        route ='logout/',
        view = views.logout_view, 
        name="logout"
    ),
    path(
        route ='singup/',
        view =views.singup, 
        name='singup'
    ),
    path(
        route ='recuperar_contrasena/',
        view = views.recuperar_contrasena, 
        name="recuperar_contrasena"
    ),
    path(
        route ='perfil/actualizar_perfil/',
        view = views.update_profile, 
        name='actualizar_perfil'
    ),
    path(
        route ='recolectores/',
        view = views.recolectores, 
        name='recolectores'
    ),
    path(
        route ='productores/',
        view = views.productores, 
        name='productores'
    ),
    path(
        route='formulario_recolectores',
        view=views.advance_update_profile,
        name="formulario_recolectores"
    ),
    path(
        route='buscar_recolector',
        view=views.buscar_recolector,
        name = 'buscar_recolector'
    ),
    path(
        route='aceptar_recolector/<int:id_info>',
        view=views.aceptar_recolector,
        name = 'aceptar_recolector'
    ),
    path(
        route='aceptar_productor/<int:id>',
        view=views.aceptar_productor,
        name = 'aceptar_productor'
    ),
    path(
        route='rechazar_visualizacion/<str:tipo>/<int:id>',
        view=views.rechazar_visualizacion,
        name = 'rechazar_visualizacion'
    ),
    path(
        route='datos_usuario/<int:id>',
        view=views.datos_usuario,
        name = 'datos_usuario'
    ),
]

users/models.py
''' Users models '''

from django.db import models


from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    '''
        Profile model
        Proxy model that extends ther base data with other information
    '''
    user = models.OneToOneField(User, on_delete = models.CASCADE)

    direction = models.CharField(max_length= 100, blank=False)
    phone_number = models.CharField(max_length=15, blank=True)
    person_type = models.IntegerField(blank=True, null=True)

    profile_picture = models.ImageField(upload_to='users/pictures',blank=True,null=True)
    company_name = models.CharField(max_length=200,blank=True)
    is_collector = models.BooleanField(default=True)
    is_productor = models.BooleanField(default=False)

    dni = models.CharField(max_length=20)
    update_counter = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now = True)

    def __str__(self):
        '''return username '''
        return self.user.username


class Info_Recolector(models.Model):
    '''
        Define los datos que solo son del recolector
    '''
    profile = models.OneToOneField(Profile, on_delete = models.CASCADE)

    description = models.TextField(max_length=300)

    plastic = models.BooleanField(default=False)
    plastic_price = models.BigIntegerField(default=False)
    cardboard = models.BooleanField(default=False)
    cardboard_price = models.BigIntegerField(default=False)
    paper = models.BooleanField(default=False)
    paper_price = models.BigIntegerField(default=False)
    glass = models.BooleanField(default=False)
    glass_price = models.BigIntegerField(default=False)
    trash = models.BooleanField(default=False)
    trash_price = models.BigIntegerField(default=False)
    metal = models.BooleanField(default=False)
    metal_price = models.BigIntegerField(default=False)


    #metadata
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now = True)

    def __str__(self):
        '''return username '''
        return self.profile.user.username


class VProductorRecolector(models.Model):
    productor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="productor_v", null=True)
    recolector = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recolector_v", null=True)


    autoriza_recolector = models.CharField(max_length=1)
    autoriza_productor = models.CharField(max_length=1)

    #metadata
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now = True)
    class Meta:
        unique_together = ('productor', 'recolector',)




'''
    Como hacer insertar registros y hacer busquedas ? 

    from app.models import class #se debe importar la clase a instanciar para cualquier caso
    #luego se instancia un objeto de ese tipo

    nombre_clase = Clase( atributo_1 = 'nombre', atributo_2 = '')  
    nombre_clase.save()

    #otra forma sería así, directamente 
    nombre_clase = Clase.objects.create(atributo_1 = 'nombre', atributo_2 = '')

    #para buscar uno solo escribir    

    objeto_buscado = Class.objects.get( usuario = 'Miller')# equivalencias exactas
    # para busquedas que coincidan con ... o demás es 
    varios_resultados = Class.objects.filter(usuario__endswith = 'Hurtado' ) # esta consulta me vota varios usuarios
    varios_resultados = Class.objects.all() # devuelve todo de la bd
    # el get solo me trae un resultado, con el filte puedo aplicar filtros xD y me devuelve varios registros de bd
    # Existen más filtros, para eso consulte la documentacion de django  3.2.4
    # para actualizar varios datos con la opción .update(valores)
    varios_resultados = Class.objects.filter(usuario__endswith = 'Hurtado' ).update(nombre= 'todos somos miller ahora')# esto cambia el nombre a  todos los usuarios que terminan en hurtado
    #update devuelve un entero del numero de registros que actualizó

'''

econciencia/forms.py
from django import forms
from django.contrib.auth.forms import  UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email= forms.EmailField()
    password1 = forms.CharField(label='Contraseña',widget=forms.PasswordInput  )
    password2 = forms.CharField(label='Contraseña',widget=forms.PasswordInput  )
    
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        help_texts = {k:"" for k in fields }

econciencia/views.py
from django.http import HttpResponse
import datetime
from django.shortcuts import render, redirect
from .forms import UserRegisterForm
from django.contrib import messages
from posts.models import Post



def home(request ): # primera vista 
    
    if request.user.id != None:
        profile = request.user.profile
    else:
        profile = ""
    context = {
        'profile': profile
    }
    return render(request, 'home.html',context)

users/views.py
'''users views'''

'''Otras cositas'''
import json
from math import prod
from django.db import IntegrityError
from datetime import datetime


# django
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from notifications_app.models import BroadcastNotification

#forms 
from users.forms import ProfileForm, SingUpForm, AdvanceProfileForm
from users.models import Info_Recolector, Profile, VProductorRecolector

# except careverga
from django.contrib.auth.models import User




def login_view(request):
    '''Login view'''
    if request.method == 'POST':
       
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request,username=username, password= password)
        if user:
            login(request,user)
            return redirect('posts:latest_posts')
        else:
            return render(request, 'users/login.html',
            {
                'error': { 
                    'tipo' : 'error',
                    'titulo': 'Error',
                    'texto': 'Usuario y contraseña invalidos',
                    'tiempo': '2000'
                    }
            })

    return render(request, 'users/login.html')


@login_required
def logout_view(request):
    '''logout user'''
    logout(request)
    return redirect('users:login')

def singup(request):
    '''sing up view'''
    
    if(request.method == "POST"):
        form = SingUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else: 
        form = SingUpForm()

    return render(request,'users/singup.html',{
        'form':form
    })


def recuperar_contrasena(request):
    pass

def update_profile(request):
    #import pdb;pdb.set_trace()
    profile = request.user.profile   
    form_advance = ''
    if request.method == 'POST':

        form = ProfileForm(request.POST, request.FILES)
        
        if profile.update_counter == 1:
            updated_request = request.POST.copy()
            updated_request.update({'person_type': profile.person_type})
            updated_request.update({'dni': profile.dni})
            form = ProfileForm(updated_request, request.FILES)

        if form.is_valid():
            data = form.cleaned_data
            profile.company_name = data['company_name']
            profile.direction = data['direction']
            profile.phone_number = data['phone_number']
            profile.profile_picture = data['profile_picture']
            profile.dni = data['dni']
            profile.person_type = data['person_type']
            profile.save()
            return redirect( 'users:actualizar_perfil' )

    else:
        form = ProfileForm()
        if(profile.is_collector == 1):
            form_advance = AdvanceProfileForm()         
    
    if(profile.is_collector == 1):
            info_recolector = Info_Recolector.objects.get(profile = profile)
    else:
        info_recolector = ''



    bandera = 0
    if(profile.update_counter == 1):
        bandera = 1


    return render(request, 'users/actualizar_perfil.html',{
        'profile': profile,
        'info_recolector':info_recolector,
        'user': request.user,
        'form': form,
        'form_advance': form_advance,
        'bandera': bandera
    })


@login_required
def advance_update_profile(request):
    profile = request.user.profile
    if request.method == 'POST':
        form_advance = AdvanceProfileForm(request.POST)
        #import pdb;pdb.set_trace()
        if form_advance.is_valid():
            
            form_advance.save(profile)
            return redirect( 'users:actualizar_perfil' )
        
        return redirect('users:actualizar_perfil')

@login_required
def recolectores(request):
    profile = request.user.profile
    #buscar recolectores por usuario en 

    verificado_uno = VProductorRecolector.objects.filter(autoriza_productor = 1).filter(productor = request.user).values_list('recolector_id', flat=True)


    recolectores = Info_Recolector.objects.all()
    context ={
        'profile': profile,
        'user': request.user,
        'aceptados': verificado_uno,
        'recolectores':recolectores,
    }
    return render(request, 'users/recolectores.html',context)



@login_required
def productores(request):
    profile = request.user.profile
    usuarios_aceptados = VProductorRecolector.objects.filter(recolector= request.user).filter(autoriza_productor = 1)
    doble_verificado = VProductorRecolector.objects.filter(recolector= request.user).filter(autoriza_recolector = 1).values_list('productor_id', flat=True)

    context = {
        'profile': profile,
        'user': request.user,
        'productores': usuarios_aceptados,
        'aceptados': doble_verificado
    }
    return render(request, 'users/productores.html',context)




@login_required
def buscar_recolector(request):
    if request.method == 'POST':
        return 0
    else:
        texto = request.GET['texto_usuario']
        residuo = request.GET['residuo']
        filtro_residuo = Q(profile__company_name__contains=texto)
        if(residuo == 'plastic'):
            filtro_residuo = Q(plastic = 1)
        elif(residuo == 'glass'):
            filtro_residuo = Q(glass = 1)
        elif(residuo == 'metal'):
            filtro_residuo = Q(metal = 1)
        elif(residuo == 'cardboard'):
            filtro_residuo = Q(cardboard = 1)
        elif(residuo == 'trash'):
            filtro_residuo = Q(trash = 1)
        elif(residuo == 'paper'):
            filtro_residuo = Q(paper = 1)
        recolectores = Info_Recolector.objects.filter( 
            (Q(profile__user__username__contains=texto) | 
            Q(profile__company_name__contains=texto)) & 
            filtro_residuo)
        data = {}
        i= 0
        for recolector in recolectores:
            data[i] = {
                'company_name'  : recolector.profile.company_name,
                'username': recolector.profile.user.username, 
                'description': recolector.description,
                'plastic'       : recolector.plastic,
                'glass'        : recolector.glass,
                'metal'        : recolector.metal,
                'cardboard'    : recolector.cardboard,
                'trash'        : recolector.trash,
                'paper'        : recolector.paper
                }
            i = i+1
        return JsonResponse(data)

@login_required
def datos_usuario(request, id):

    user = User.objects.get(id = id)
    recolector = request.user
    profile = Profile.objects.get(user = user)
    visible = VProductorRecolector.objects.get(recolector = recolector, productor = user)
    if(visible.autoriza_productor == '1' and visible.autoriza_recolector == '1'):
        context = {
        'telefono_productor': profile.phone_number,
        'correo_productor':user.email,
        }
    else:
        context = {
        'telefono_productor': '',
        'correo_productor':'',
        }
    return JsonResponse(context) 

@login_required
def aceptar_recolector(request, id_info):
    now = datetime.now()
    print(now.strftime("%Y-%m-%d %H:%M:%S"))
    info = Info_Recolector.objects.get(id = id_info)
    recolector = info.profile.user
    productor = request.user
    mensaje = 'El usuario '+ productor.username +' quiere comunicarse contigo'

    existencia = VProductorRecolector.objects.get(recolector = recolector, productor = productor)


    if(existencia.autoriza_productor == '0'):
        existencia.autoriza_productor = 1
        existencia.save()
        notificacion = BroadcastNotification(
            mensaje = mensaje, 
            estado = 0, 
            broadcast_on= now.strftime("%Y-%m-%d %H:%M:%S"), 
            usuario_propietario = recolector, 
            usuario_enviador=productor,
            direccion = 'users:productores'
        )
        notificacion.save()
        return JsonResponse({
            'titulo' : 'Exito !',
            'mensaje': 'Notificacion enviada, pronto se comunicarán contigo',
            'tipo': 'success'
        })
    try:
        nueva_visualizacion = VProductorRecolector(
            autoriza_recolector = 0,
            autoriza_productor = 1,
            productor = productor,
            recolector = recolector
        )
        

        notificacion = BroadcastNotification(
            mensaje = mensaje, 
            estado = 0, 
            broadcast_on= now.strftime("%Y-%m-%d %H:%M:%S"), 
            usuario_propietario = recolector, 
            usuario_enviador=productor,
            direccion = 'users:productores'
        )
        nueva_visualizacion.save()
        notificacion.save()
        return JsonResponse({
            'titulo' : 'Exito !',
            'mensaje': 'Notificacion enviada, pronto se comunicarán contigo',
            'tipo': 'success'
        })
    except IntegrityError:
        return JsonResponse({
            'titulo' : 'Ups !',
            'mensaje': 'Ocurrió un error inesperado, comprueba que no hayas  aceptado a este recolector antes',
            'tipo': 'error'
        })
    
@login_required
def aceptar_productor(request, id):
    now = datetime.now()
    productor  = User.objects.get(id = id)
    recolector = request.user
    mensaje = 'El recolector '+ recolector.username +' aceptó la comunicación contigo'

    visualizacion = VProductorRecolector.objects.get(
        productor = productor,
        recolector = recolector
    )
    datos_productor = Profile.objects.get(user = productor)


    if(visualizacion.autoriza_recolector == '0'):
        visualizacion.autoriza_recolector = 1
        visualizacion.save()

        notificacion = BroadcastNotification(
            mensaje = mensaje, 
            estado = 0, 
            broadcast_on= now.strftime("%Y-%m-%d %H:%M:%S"), 

econciencia/templates/users/login.html
{% extends 'users/base.html'%}

{% block title %}
	Econciencia - Login
{% endblock %}

{%block body%}       
	{% load static %}
	
	<form class="login" method="post" action="{% url 'users:login'%}">
		{% csrf_token %}
		<div class="login__field">
			<svg class="bi login__icon" width="20" height="20" fill="currentColor">
				<use xlink:href="{% static 'css/bootstrap-icons/bootstrap-icons.svg'%}#person-fill"/>
			</svg>
			<input type="text" name="username" class="login__input" placeholder="Usuario">
		</div>
		<div class="login__field">
			<svg class="bi login__icon" width="20" height="20" fill="currentColor">
				<use xlink:href="{% static 'css/bootstrap-icons/bootstrap-icons.svg'%}#lock-fill"/>
			</svg>
			<input type="password" name ="password" class="login__input" placeholder="Contraseña">
		</div>
		<button class="button login__submit">
			<span class="button__text">Iniciar Sesión</span>
			<svg class="bi button__icon" width="20" height="20" fill="currentColor">
				<use xlink:href="{% static 'css/bootstrap-icons/bootstrap-icons.svg'%}#caret-right-fill"/>
			</svg>
			
		</button>
	</form>
	<div class="social-login">
		<h4></h4>
		<div class="social-icons">
			<a href="#" class="social-login__icon fab fa-instagram">
				<!--<svg class="bi button__icon" width="20" height="20" fill="currentColor">
					<use xlink:href="{% static 'css/bootstrap-icons/bootstrap-icons.svg'%}#facebook"/>
				</svg>-->
			</a>
			<p><a href="{% url 'users:singup' %}" class="">Registrarse</a></p>
			
		</div>
		<div>
			<p><a href="{% url 'users:recuperar_contrasena' %}" class="">Olvidé mi contraseña</a></p>
		</div>
	</div>


{% endblock %}

{% block stylesheets %}

<style>
	@import url("https://fonts.googleapis.com/css?family=Raleway:400,700");

	* {
		box-sizing: border-box;
		margin: 0;
		padding: 0;
		font-family: Raleway, sans-serif;
	}
	
	body {
		background: linear-gradient(60deg, #fff, #2FA4FF);
	}
	a{
		
		text-decoration: none;
		font-family: Raleway, sans-serif;
		color: #020629;
	}
	.container {
		display: flex;
		align-items: center;
		justify-content: center;
		min-height: 100vh;
	}
	
	.screen {
		background: linear-gradient(90deg, #2FA4FF, #0E185F);
		position: relative;
		height: 600px;
		width: 360px;
		box-shadow: 0px 0px 24px #020629;
	}
	
	.screen__content {
		z-index: 1;
		position: relative;
		height: 100%;
	}
	
	.screen__background {
		position: absolute;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;
		z-index: 0;
		-webkit-clip-path: inset(0 0 0 0);
		clip-path: inset(0 0 0 0);
	}
	
	.screen__background__shape {
		transform: rotate(45deg);
		position: absolute;
	}
	
	.screen__background__shape1 {
		height: 520px;
		width: 520px;
		background: #fff;
		top: -50px;
		right: 120px;
		border-radius: 0 72px 0 0;
	}
	
	.screen__background__shape2 {
		height: 220px;
		width: 220px;
		background: #00ffdd;
		top: -172px;
		right: 0;
		border-radius: 32px;
	}
	
	.screen__background__shape3 {
		height: 540px;
		width: 190px;
		background: linear-gradient(270deg, #2fa4ff, #E8FFC2);
		top: -24px;
		right: 0;
		border-radius: 32px;
	}
	
	.screen__background__shape4 {
		height: 400px;
		width: 200px;
		background: #00ffdd;
		top: 420px;
		right: 50px;
		border-radius: 60px;
	}
	
	.login {
		width: 320px;
		padding: 30px;
		padding-top: 156px;
	}
	
	.login__field {
		padding: 20px 0px;
		position: relative;
	}
	
	.login__icon {
		position: absolute;
		top: 30px;
		color: #0e185f;
	}
	
	.login__input {
		border: none;
		border-bottom: 2px solid #d1d1d4;
		background: none;
		padding: 10px;
		padding-left: 24px;
		font-weight: 700;
		width: 75%;
		transition: 0.2s;
	}
	
	.login__input:active,
	.login__input:focus,
	.login__input:hover {
		outline: none;
		border-bottom-color: #E8FFC2;
	}
	
	.login__submit {
		background: #fff;
		font-size: 14px;
		margin-top: 30px;
		padding: 16px 20px;
		border-radius: 26px;
		border: 1px solid #d4d3e8;
		text-transform: uppercase;
		font-weight: 700;
		display: flex;
		align-items: center;
		width: 100%;
		color: #0e185f;
		box-shadow: 0px 2px 2px #0e185f;
		cursor: pointer;
		transition: 0.2s;
	}
	
	.login__submit:active,
	.login__submit:focus,
	.login__submit:hover {
		border-color: #0e185f;
		outline: none;
	}
	
	.button__icon {
		font-size: 24px;
		margin-left: auto;
		color: #0e185f;
	}
	
	.social-login {
		position: absolute;
		height: 140px;
		width: 160px;
		text-align: center;
		bottom: 0px;
		right: 0px;
		color: #fff;
	}
	
	.social-icons {
		display: flex;
		align-items: center;
		justify-content: center;
	}
	
	.social-login__icon {
		padding: 20px 10px;
		color: #fff;
		text-decoration: none;
		text-shadow: 0px 0px 8px #02526D;
	}
	
	.social-login__icon:hover {
		transform: scale(1.5);
	}
	

	
</style>


{% endblock %}

{% block javascripts %}

	{{block.super}}
	
{% endblock %}

econciencia/templates/users/recolectores.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<div class="container mt-5">
    <form id = "busqueda_recolectores" class="d-flex" role="search" action="{% url 'users:buscar_recolector'%}">
        <input name = "texto_usuario" class="form-control me-2" type="search" placeholder="Nombre de compañia" aria-label="Search">
        <select class="form-control me-1" name="residuo" id="residuo">
            <option value = 0 selected>Seleccione el residuo a buscar</option>
            <option value="plastic">Plastico</option>
            <option value="glass">Vidrio</option>
            <option value="metal">Metal</option>
            <option value="cardboard">Cartón</option>
            <option value="trash">Organicos</option>
            <option value="paper">Papel</option>
        </select>
        <button class="btn btn-primary" type="submit">Buscar</button>
    </form>
</div>

<div class="container">
    <div class="row mt-3" id="recolectores">
        {% for recolector in recolectores %}
        <div class="col-12 col-sm-12 col-md-4 mb-2">
            <div class="card text-center border" style="height:100%;">
                <div class="card-header text-center text-uppercase justify-content-center">
                    {% if recolector.profile.company_name == null or recolector.profile.company_name == "" %}
                        {{recolector.profile.user.username}}   
                    {% else %}
                     {{recolector.profile.company_name}}
                    {% endif %}
                </div>
                <div class="card-body">
                    
                    <p class="card-text">
                        {% if recolector.description %}
                            {{recolector.description}}
                        {% else %}
                            No hay descripción
                        {% endif %}
                    </p>
                    <h4 class="card-text">Residuos que recolectan</h4>
                    <ul class="lista_residuos">
                        {% if recolector.plastic == 1%}     <li class="text-left">Plastico</li> {%endif%}
                        {% if recolector.glass == 1%}       <li class="text-left">Vidrio</li> {%endif%}
                        {% if recolector.metal == 1%}       <li class="text-left">Metal</li> {%endif%}
                        {% if recolector.cardboard == 1%}   <li class="text-left">Cartón</li> {%endif%}
                        {% if recolector.trash == 1%}       <li class="text-left">Organicos</li> {%endif%}
                        {% if recolector.paper == 1%}       <li class="text-left">Papel</li> {%endif%}
                    </ul>
                </div>
                <div class="card-footer">
                    {% if recolector.profile.user.id in  aceptados %}
                        <button id= 'aceptar{{recolector.id}}' type="button" class="btn btn-primary m-1" onclick="aceptar_recolector(  {{recolector.id}}  ) " disabled >Aceptar</button>
                    {% else %}
                        <button id= 'aceptar{{recolector.id}}' type="button" class="btn btn-primary m-1" onclick="aceptar_recolector(  {{recolector.id}}  ) " >Aceptar</button>
                    {% endif %}
                    <button type="button" class="btn btn-secondary m-1" onclick="rechazar_visualizacion('recolector','{{recolector.profile.user.id}}')">Rechazar</button>
                </div>
            </div>
        </div>
        
        {% endfor %}
    </div>
</div>


<div class="modal fade" id="modal_confirmar" tabindex="-1" aria-labelledby="modal_confirmarLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modal_confirmarLabel">Información </h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="mb-3">
                <label for="user" class="col-form-label">Notificacion enviada exitosamente</label>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
</div>

{% endblock %}

{% block stylesheets %}
    {{block.super}}
    <link rel="stylesheet" href="{% static 'css/consulta.css'%}">
{% endblock%}

{% block javascripts %}
    {{block.super}}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script scr="https://cdn.datatables.net/plug-ins/1.12.1/i18n/es-ES.json"></script>
    <script src="{% static 'js/consulta.js'%}"></script>
{% endblock%}