canecas/urls.py
#Django
from django.urls import path, include


#from rest_framework import routers

#rest_framework
from rest_framework import routers

#views

from canecas import views
app_name = 'canecas'

router = routers.DefaultRouter()
router.register(r'canecas_api', views.CanecaApiView,basename='canecas_api')

urlpatterns = [
    path('', include(router.urls)),
    path('<int:pk>/', include(router.urls)),
    
    path('mi_caneca/<int:id>/', views.mi_caneca,name='mi_caneca' ),
    path('entregas/',views.entregas, name='entregas'),
    path('consultas/',views.consultar_canecas, name='consultas'),
    path('eliminar/<int:id>/',views.eliminar_canecas, name='eliminar'),
    path('buscar_canecas/<int:id_usuario>/', views.buscar_canecas,name='buscar_canecas'),
]

econciencia/urls.py
from django.contrib import admin


from django.conf.urls.static import static
from django.conf import settings

from canecas import views as caneca_views

from rest_framework import routers


#router = routers.DefaultRouter()
#router.register(r'canecas_api', caneca_views.CanecaApiView)




from django.urls import path, include
from econciencia import views as econciencia_views


urlpatterns = [


    path('admin/', admin.site.urls),


    path('',include(('posts.urls', 'posts'), namespace='posts' )),
    path('users/',include(('users.urls', 'users'), namespace='users' )),
    path('caneca/',include(('canecas.urls', 'canecas'), namespace='canecas' )),


    path('',econciencia_views.home,name="home"),


] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

posts/urls.py
''' Posts urls'''


#Django

from django.urls import path

#Models

from posts import views


urlpatterns =[
    path(
        route= 'posts/latest_posts/',
        view = views.latest_posts,
        name="latest_posts"
    ),
]

canecas/models.py
from asyncio.windows_events import NULL
from datetime import date
from multiprocessing import parent_process
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from notifications_app.models import BroadcastNotification
from datetime import datetime



class Caneca(models.Model):
    '''Caneca'''
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=255)
    mac = models.CharField(max_length=15)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    latitud = models.CharField(max_length=200)
    longitud = models.CharField(max_length=200)
    ubicacion = models.CharField(max_length=150)

    n_peticiones = models.BigIntegerField(default=0)
    
    metal       = models.IntegerField(default=0)   
    paper       = models.IntegerField(default=0)
    glass       = models.IntegerField(default=0)
    trash       = models.IntegerField(default=0)
    plastic     = models.IntegerField(default=0)
    cardboard   = models.IntegerField(default=0)


    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now = True)

    def __str__(self):
        ''' return tittle'''
        return '{}, proveniente de la mac {}'.format(self.name, self.mac)


@receiver(post_save, sender=Caneca)
def notification_handler(sender,instance, created,**kwargs):
    #call group_send function directly to send notifications or crear una tarea dinamica con celery pero no sé como hacer esa mondá
    caneca = instance
    usuario_defatult = instance.user
    # datetime object containing current date and time
    now = datetime.now()
    if(caneca.cardboard >= 80 ):
        mensaje = f"Tu caneca está llenandose de cartón, tiene {caneca.cardboard}%"
        notificacion = BroadcastNotification(
            mensaje = mensaje, 
            estado = 0, 
            broadcast_on= now.strftime("%Y-%m-%d %H:%M:%S"), 
            usuario_propietario = usuario_defatult, 
            usuario_enviador=usuario_defatult,
            direccion = 'canecas:consultas'
        )
        notificacion.save()
    if(caneca.glass >= 80 ):
        mensaje = f"Tu caneca está llenandose de vidrio, tiene {caneca.glass}%"
        notificacion = BroadcastNotification(
            mensaje = mensaje, 
            estado = 0, 
            broadcast_on= now.strftime("%Y-%m-%d %H:%M:%S"), 
            usuario_propietario = usuario_defatult, 
            usuario_enviador=usuario_defatult,
            direccion = 'canecas:consultas'
        )
        notificacion.save()
    if(caneca.metal >= 80 ):
        mensaje = f"Tu caneca está llenandose de metal, tiene {caneca.metal}%"
        notificacion = BroadcastNotification(
            mensaje = mensaje, 
            estado = 0, 
            broadcast_on= now.strftime("%Y-%m-%d %H:%M:%S"), 
            usuario_propietario = usuario_defatult, 
            usuario_enviador=usuario_defatult,
            direccion = 'canecas:consultas'
        )
        notificacion.save()
    if(caneca.paper >= 80 ):
        mensaje = f"Tu caneca está llenandose de papel, tiene {caneca.paper}%"
        notificacion = BroadcastNotification(
            mensaje = mensaje, 
            estado = 0, 
            broadcast_on= now.strftime("%Y-%m-%d %H:%M:%S"), 
            usuario_propietario = usuario_defatult, 
            usuario_enviador=usuario_defatult,
            direccion = 'canecas:consultas'
        )
        notificacion.save()
    if(caneca.plastic >= 80 ):
        mensaje = f"Tu caneca está llenandose de plastico, tiene {caneca.plastic}%"
        notificacion = BroadcastNotification(
            mensaje = mensaje, 
            estado = 0, 
            broadcast_on= now.strftime("%Y-%m-%d %H:%M:%S"), 
            usuario_propietario = usuario_defatult, 
            usuario_enviador=usuario_defatult,
            direccion = 'canecas:consultas'
        )
        notificacion.save()
    if(caneca.trash >= 80 ):
        mensaje = f"Tu caneca está llenandose de basura, tiene {caneca.trash}%"
        notificacion = BroadcastNotification(
            mensaje = mensaje, 
            estado = 0, 
            broadcast_on= now.strftime("%Y-%m-%d %H:%M:%S"), 
            usuario_propietario = usuario_defatult, 
            usuario_enviador=usuario_defatult,
            direccion = 'canecas:consultas'
        )
        notificacion.save()

canecas/forms.py
from django import forms
from django.contrib.auth.models import User
from canecas.models import Caneca

class CreateCaneca(forms.Form):
    user = forms.CharField(min_length=4)
    name = forms.CharField(min_length=5)
    description = forms.CharField(min_length=4, max_length=30)
    mac  = forms.CharField(max_length=15)
    direction = forms.CharField(max_length=50)
    def clean_usuario(self):
        user = self.cleaned_data['usuario']
        username_use = User.objects.get(username=user)
        return username_use
    def save(self):
        '''create caneca mamadisima'''
        data = self.cleaned_data
        print(data['direction'])
        user = data['user']
        username_use = User.objects.get(username=user)

        name = data['name']
        description = data['description']
        mac = data['mac']
        ubicacion = data['direction']
        
        caneca = Caneca()
        caneca.user= username_use
        caneca.name = name
        caneca.description = description
        caneca.mac = mac
        caneca.ubicacion = ubicacion

        caneca.save()
        
    

econciencia/forms.py
from django import forms
from django.contrib.auth.forms import  UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email= forms.EmailField()
    password1 = forms.CharField(label='Contraseña',widget=forms.PasswordInput  )
    password2 = forms.CharField(label='Contraseña',widget=forms.PasswordInput  )
    
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        help_texts = {k:"" for k in fields }

canecas/views.py
#django
from pprint import pprint
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse

#Api libraries
from rest_framework.response import Response
from rest_framework import status
from rest_framework import viewsets
from rest_framework import permissions
from rest_framework.decorators import action
from canecas.serializers import CanecaSerializer



#models

from django.contrib.auth.models import User
from canecas.models import Caneca
from canecas.forms import CreateCaneca
from canecas.script_ia import model_ia

#Otras librerias
import numpy as np
import base64 
from PIL import Image
from matplotlib import pyplot as plt



class CanecaApiView(viewsets.ModelViewSet):
    """
    API endpoint that allows users to edit Canecas or predict an image.
    """

    serializer_class = CanecaSerializer
    permission_classes = [permissions.IsAuthenticated]


    @action(detail=True, methods=['post'])
    def solve_image(self, request, pk=None):
        caneca = Caneca.objects.get(pk=pk)
        
        n_peticiones = caneca.n_peticiones + 1
        caneca.n_peticiones = n_peticiones
        caneca.save()
        #print(request.POST['file'])
        
        
        if(request.POST):
            imagen = base64.b64decode(request.POST['file'])
            filename = "image.jpg"
            imagen_escribir = open(filename,'wb')   # create a writable image and write the decoding result


            imagen_escribir.write(imagen)
            #img = open(imagen)
            '''
            im = plt.imread("image.jpg")
            fig, ax = plt.subplots()
            im = ax.imshow(im, extent=[0, 300, 0, 300])
            x = np.array(range(300))
            ax.plot(x, x, ls='dotted', linewidth=2, color='red')
            plt.show()
            '''
            
            img = Image.open('image.jpg')
            image_solve = model_ia.predict_external_image(img)
           

            return Response(
                {
                    'status': '200',
                    'message': 'Your image was predict',
                    'image_solve': image_solve
                },
                status=status.HTTP_200_OK
            )
        else:
            return Response(
                {
                'status': '400',
                'message': 'Bad request, you must send a image'
                },
                status= status.HTTP_400_BAD_REQUEST
            )
    def list(self, request):
        user = request.user
        queryset = Caneca.objects.filter(user = user)
        serializer = CanecaSerializer(queryset, many=True)
        return Response(serializer.data)



    def retrieve(self, request, pk=None):
        user = request.user
        queryset = Caneca.objects.filter(user = user)#3,54,5,3
        caneca = get_object_or_404(queryset, pk=pk)
        serializer = CanecaSerializer(caneca)
        return Response(serializer.data)


    def create(self, request):
        return Response(
                {
                'status': '400',
                'message': 'You are not allowed to create or delete'
                },
                status= status.HTTP_400_BAD_REQUEST
            )

    

    def destroy(self, request, pk=None):
         return Response(
                {
                'status': '400',
                'message': 'You are not allowed to create or delete'
                },
                status= status.HTTP_400_BAD_REQUEST
            )



    def update(self, request, pk=None):
        user = request.user
        canecas_user = Caneca.objects.filter(user = user)
        caneca = Caneca()
        try:
            caneca = Caneca.objects.get(pk=pk)
            if( caneca in canecas_user ):
                
                serializer = CanecaSerializer(caneca, data = request.data, partial =True)
                
                if(serializer.is_valid()):
                    serializer.save()
                    
                    return Response(serializer.data)
                return Response(serializer.errors,status= status.HTTP_400_BAD_REQUEST)
            else:
                return Response(
                    {
                        'status': '400',
                        'message': 'Invalid Caneca id'
                    },
                    status=status.HTTP_400_BAD_REQUEST
            )
        except:
            return Response(
                {
                    'status': '400',
                    'message': 'Invalid Caneca except id'
                },
                status=status.HTTP_400_BAD_REQUEST
            )
        
        
    
    
@login_required
def mi_caneca(request,id):
    caneca = Caneca.objects.get(id=id)
    profile = request.user.profile
    
    if request.method == 'POST':
        form = CreateCaneca(request.POST)
        if form.is_valid():
            form.save()
            return redirect('canecas:consultar_caneca',id=1)
    else:
        form = CreateCaneca()


    #import pdb;pdb.set_trace()
    data = []
    
    
    
    
    data.insert(0,caneca.trash)
    data.insert(0,caneca.cardboard)
    data.insert(0,caneca.glass)
    data.insert(0,caneca.metal)
    data.insert(0,caneca.paper)
    data.insert(0,caneca.plastic)

    context = {
        'profile': profile,
        'form': form,
        'caneca': caneca,
        'data': data
    }

    return render(request, 'canecas/mi_caneca.html',context)


#@login_required
def entregas(request):
    #profile = request.user.profile
    #'profile': profile,
    context = {
    }
    return render(request, 'canecas/entregas.html',context)


@login_required
def consultar_canecas(request):
    profile = request.user.profile
    
    if request.method == 'POST':
        form = CreateCaneca(request.POST)
        if form.is_valid():
            form.save()
            return redirect('canecas:consultas')
    else:
        form = CreateCaneca()
    #user = request.user
    canecas_user = Caneca.objects.filter(user = request.user)
    
    context = {
        'profile': profile,
        'canecas': canecas_user,
        'form': form
    }
    return render(request, 'canecas/consultas.html',context)


@login_required
def eliminar_canecas(request, id):
    profile = request.user.profile
    caneca = get_object_or_404(Caneca, id=id)
    caneca.delete()
    context = {
        'profile': profile,
        'error': { 
                    'tipo' : 'success',
                    'titulo': 'Eliminado',
                    'texto': 'La caneca fue eliminada',
                    'tiempo': '2022'
                }
    }
    return redirect('canecas:consultas')

@login_required
def buscar_canecas(request,id_usuario):
    usuario = User.objects.get(id = id_usuario)
    canecas = Caneca.objects.filter(user = usuario)
    data = {}
    i= 0
    for caneca in canecas:
        data[i] = {
            'name': caneca.name, 
            'description': caneca.description,
            'plastic'       : caneca.plastic,
            'glass'        : caneca.glass,
            'metal'        : caneca.metal,
            'cardboard'    : caneca.cardboard,
            'trash'        : caneca.trash,
            'paper'        : caneca.paper
        }
        i = i+1
    return JsonResponse(data)

econciencia/views.py
from django.http import HttpResponse
import datetime
from django.shortcuts import render, redirect
from .forms import UserRegisterForm
from django.contrib import messages
from posts.models import Post



def home(request ): # primera vista 
    
    if request.user.id != None:
        profile = request.user.profile
    else:
        profile = ""
    context = {
        'profile': profile
    }
    return render(request, 'home.html',context)

econciencia/templates/canecas/consultas.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<div class="m-5  d-flex justify-content-center row completo">
    <div class="row p-0">
        <div class="col-md-6"></div>
        <div class="col-md-6 texto_derecha">

            <button type="button" class="mb-3 btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                <svg class="bi login__icon" width="30" height="30" fill="currentColor">
                    <use xlink:href="{% static 'css/bootstrap-icons/bootstrap-icons.svg'%}#plus-square-dotted"/>
                </svg> Agregar Caneca
                
            </button>
        </div>
    </div>
    <div>
        <table id="example" class="table  table-bordered table-responsive caption-top" >
            <caption>Lista de Canecas</caption>
            <thead class="table-otro">
                <tr class="text-center">
                    <th class="text-center" scope="col">#</th>
                    <th class="text-center" scope="col">Nombre</th>
                    <th class="text-center" scope="col">MAC</th>
                    <th class="text-center" scope="col">Dirección</th>
                    <th class="text-center" scope="col">Eliminar</th>
                </tr>
            </thead>
            <tbody>
                {% for caneca in canecas %}
                <tr>
                    <td>{{caneca.id}}</td>
                    <td><a href="{% url 'canecas:mi_caneca' id=caneca.id %}">{{caneca.name}}</a></td>
                    <td>{{caneca.mac}}</td>
                    <td>{{caneca.ubicacion}}</td>
                    <td class="text-center">
                        <a href="{% url 'canecas:eliminar' id=caneca.id %}" class="btn btn-primary m-0">Eliminar</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>   


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class=" modal-header">
                <h5 class="col-md-10 text-center modal-title " id="exampleModalLabel">Agrega tu Caneca</h5>
                <button type="button" class="btn-close  btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="post" action="{% url 'canecas:consultas' %}">
                {% csrf_token %}
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="user" class="col-form-label">Usuario:</label>
                        <input type="text" class="form-control" name="user" id="user" value ="{{ request.user.username}}" readonly>
                    </div>
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Nombre:</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Nombre caneca">
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Descripción:</label>
                        <input type="text" class="form-control" name="description" id="description" placeholder="Descripción caneca">
                    </div>
                    <div class="mb-3">
                        <label for="mac" class="col-form-label">MAC:</label>
                        <input type="text" class="form-control" id="mac" name = "mac" placeholder="Mac de la caneca">
                    </div>
                    <div class="mb-3">
                        <label for="direction" class="col-form-label">Ubicación:</label>
                        <input type="text" class="form-control" id="direction" name = "direction" placeholder="Dirección Caneca">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block stylesheets %}
    {{block.super}}
    <link rel="stylesheet" href="{% static 'css/consulta.css'%}">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css">
{% endblock%}

{% block javascripts %}
    {{block.super}}
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script scr="https://cdn.datatables.net/plug-ins/1.12.1/i18n/es-ES.json"></script>
    <script src="{% static 'js/consulta.js'%}"></script>
{% endblock%}

econciencia/templates/canecas/entregas.html
 {% extends "base.html" %}
  
  
{% block scripts_header %}
  <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
{% endblock scripts_header %}
  
    <!-- jsFiddle will insert css and js -->

{% block body %}
  <h3>Mapa de los recolectores</h3>
  <!--The div element for the map -->
  <div id="map" class="mapa"></div>
  <div>
  <!-- 
    The `defer` attribute causes the callback to execute after the full HTML
    document has been parsed. For non-blocking uses, avoiding race conditions,
    and consistent behavior across browsers, consider loading using Promises
    with https://www.npmjs.com/package/@googlemaps/js-api-loader.
  -->
{% endblock %}


{% block javascripts %}
  {{block.super}} 
  <script
  
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6rAbvp1ZMcUIQ2o_PnAvloNVuW-I7vOQ&callback=initMap&v=weekly"
      defer
    ></script>
    <script>
      let rectangle;
      let map;
      let infoWindow;
      let infomarker;
      let marker;

      function initMap() {
        map = new google.maps.Map(document.getElementById("map"), {
          center: { lat: 4.626677296847028, lng: -73.80432763671872 },
          zoom: 9,
        });

        const bounds = {
          north:4.7 ,
          south:4.626677296847028 ,
          east: -73.6,
          west: -73.80432763671872,
        };

        // Define the rectangle and set its editable property to true.
        rectangle = new google.maps.Rectangle({
          bounds: bounds,
          editable: true,
          draggable: true,
        });
        
        
        rectangle.setMap(map);
        
        const myLatLng = { lat: 4.626677296847028, lng: -73.80432763671872 };
        marker = new google.maps.Marker({
          position: myLatLng,
          draggable: true,
          map,
          title: "Hello World!",
        });
        // Add an event listener on the rectangle.
        rectangle.addListener("bounds_changed", showNewRect);
        marker.addListener("dragend", showMarker);
        // Define an info window on the map.
        infoWindow = new google.maps.InfoWindow();
        infomarker = new google.maps.InfoWindow();
      }

      /** Show the new coordinates for the rectangle in an info window. */
      function showNewRect() {
        const ne = rectangle.getBounds().getNorthEast();
        const sw = rectangle.getBounds().getSouthWest();
        const contentString =
          "<b>Rectangle moved.</b><br>" +
          "New north-east corner: " +
          ne.lat() +
          ", " +
          ne.lng() +
          "<br>" +
          "New south-west corner: " +
          sw.lat() +
          ", " +
          sw.lng();

        // Set the info window's content and position.
        infoWindow.setContent(contentString);
        infoWindow.setPosition(ne);
        infoWindow.open(map);
      }
      function showMarker() {
        const position = marker.getPosition();
        const contentString =
          "<b>Marker</b><br>" +
          "Latitud " +
          position.lat() +
          ", Longitud" +
          position.lng() +
          "<br>";

        // Set the info window's content and position.
        infomarker.setContent(contentString);
        infomarker.open({
            anchor: marker,
            map,
            shouldFocus: false,
          });

      }
      window.initMap = initMap;

    </script>
{% endblock %}
    
{% block stylesheets %}
    {{block.super}}
  <style>
    .mapa {
      height: 400px;
      /* The height is 400 pixels */
      width: 80%;
      /* The width is the width of the web page */
    }
  </style>
{% endblock %}

econciencia/templates/canecas/mi_caneca.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="mt-5 d-flex justify-content-center row completo">
    <div class=" col-md-6  caneca text-center" >
        <div class="circulo">
            <div class="circuloInterno">
                <div class="sombra">
                </div>
            </div>
        </div>
        <div class="rectangulo">
        </div>
        <div class="cuadrado">
            <div class="cuadradoInterno text-left">
                <h3>
                    <p>{{caneca.name}}</p>
                    <p>{{caneca.description}}</p>
                </h3>
            </div>
        </div>
    </div>
    <div class="col-6 d-flex flex-column justify-content-center align-items-center estadisticas">
        <div class=" mb-5 p-2 align-self-center estado">
            <div class="triangulo"></div>
            <div class="triangulo1"></div>
        </div>
        <figure class="mb-5 p-2 align-self-center highcharts-figure">
            <div id="container"></div>
        </figure>
    </div>
</div>    
{% endblock %}

{% block stylesheets %}
    {{block.super}}
    <link rel="stylesheet" href="{% static 'css/caneca.css'%}">

{% endblock%}

{% block javascripts %}
    {{block.super}}
    {% if form.errors %}
        {{ form.errors|json_script:"errores" }}
        <script>
            var errores = JSON.parse(document.getElementById('errores').textContent);
            var consolidado = "";
            for (const error in errores) {
                consolidado += `${error}:\n\t ${errores[error]}\n`;
            }
            send_notification( 'error','Error',consolidado,'3000')
            
        </script>
    {% endif %}
    <script>
        _values = {{data|safe}};
    </script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/data.js"></script>
    <script src="https://code.highcharts.com/modules/drilldown.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
    <script src="{% static 'js/caneca.js'%}"></script>
{% endblock%}